trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  imageName: 'currency-api'

steps:

- task: Docker@2
  displayName: Build and push image
  inputs:
    containerRegistry: 'MyACRConnection'
    repository: 'currency-api'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    tags: |
      latest
      $(Build.BuildId)

- task: Kubernetes@1
  displayName: Deploy to Kubernetes
  inputs:
    connectionType: 'Kubernetes Service Connection'
    kubernetesServiceEndpoint: 'MyK8sConnection'
    command: apply
    useConfigurationFile: true
    configuration: k8s/deployment.yaml
